name: flexiapp

services:

    webapp:
        build: .
        image: flexiapp/webapp
        container_name: flexiapp-webapp
        ports:
            - "9002:80"
        restart: always
        tty: true
        volumes:
            - ./src:/app/src
